MVCAssignment/Controllers/BookReadingEventController.cs
using System.Web.Mvc;
using BL;
using MVCAssignment.Models;
using Shared;
using MVCAssignment.Helper;
using System.Collections.Generic;
using System;

namespace MVCAssignment.Controllers
    {
    public class BookReadingEventController : Controller
    {

        string UserName;
        public string GetUserName
            {
            get
                {
                if (User.Identity.IsAuthenticated)
                    {
                    UserName = User.Identity.Name;
                    }
                return UserName;
                }
               
            }
       
        public ActionResult AllEvents()
            {
            AllEventsBL allEvents = new AllEventsBL();
            IEnumerable<Event> events = allEvents.GetEvents;
             
              return View(new EventToEventModelHelper().GetEventModels(events));
              
            }
        

        
        public ActionResult MyEvents()
            {
            string UserName=GetUserName;
            MyEventsBL getMyEventsBL = new MyEventsBL();
            var myEvents = getMyEventsBL.GetMyEvents(UserName);
            return View(new EventToEventModelHelper().GetEventModels(myEvents));
            }


       public ActionResult EventsInvitedTo()
            {
            string UserEmail = new UserEmailBL().GetUserEmail(User.Identity.Name);
            InvitedToBL invitedToBL = new InvitedToBL();
            var invitedEvents = invitedToBL.GetInvitedTo(UserEmail);
            return View(new EventToEventModelHelper().GetEventModels(invitedEvents));
            }
       

      
        [HttpGet]
        public ActionResult CreateEvent()
            {
           
            return View();
            }
        
        [ActionName("CreateEvent")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateEventPost([Bind(Include = "Title, Date, StartTime,Duration,OtherDetails,Type,InviteByEmail,Location,Description")]EventModel model)
            {
                if(ModelState.IsValid)
                {
                model.UserId =User.Identity.Name;
                
                Event evt = new EventModelToEventHelper().EventModelToEventMapping(model);

                if(new CreateEventBL().CreateEvent(evt))

                return RedirectToAction("About","Home");

                
                }
            ViewBag.Message = "Title Already exists";
            return View(model);

            }
        
        
       
        public ActionResult ViewEvent(int eventId)
            {
             EventBL evt = new EventBL();
            EventModel eventModel = new EventToEventModelHelper().EventToEventModelMapping(evt.GetEvent(eventId));
            if (eventModel.InviteByEmail != null)
                {
                eventModel.Count = eventModel.InviteByEmail.Split(',').Length;
                }
            else
                {
                eventModel.Count = 0;
                }
            ViewBag.DisplayDescription = (eventModel.Description != null) ? true : false;
            ViewBag.DisplayOtherDetails = (eventModel.OtherDetails != null) ? true : false;
            ViewBag.DisplayDuration = (eventModel.Duration != null) ? true : false;
            ViewBag.DisplayCount = (eventModel.Count != 0) ? true : false;
            ViewBag.DisplayEditLink = ((eventModel.Date.Date > DateTime.Now.Date.Date)
                || ((eventModel.Date.Date == DateTime.Now.Date.Date) && (eventModel.StartTime.Date.TimeOfDay > DateTime.Now.Date.TimeOfDay)))
                &&(eventModel.UserId.Equals(User.Identity.Name,StringComparison.OrdinalIgnoreCase)||User.IsInRole("Admin"))
                ? true : false;
            
            return View(eventModel);
            }

        [HttpGet]
      
        public ActionResult EditEvent(int eventId)
            {
            EventBL eventBL = new EventBL();
            EventModel model = new EventToEventModelHelper().EventToEventModelMapping(eventBL.GetEvent(eventId));
            return View(model);
            }
        
        
        [HttpPost]
        [ActionName("EditEvent")]
        
        public ActionResult EditEventPost(EventModel eventModel)
            {
            if (ModelState.IsValid)
                {
                EditEventBL editEvent = new EditEventBL();
                editEvent.EditEvent(new EventModelToEventHelper().EventModelToEventMapping(eventModel));
                return RedirectToAction("ViewEvent",new { eventModel.EventId});
                }
            else
                return View();
            
            }

        public ActionResult DeleteEvent(int eventId)
            {
            DeleteEventBL deleteEventBL = new DeleteEventBL();
            deleteEventBL.DeleteEvent(eventId);
            return RedirectToAction("About","Home");
            }

        [HttpGet]
        public ActionResult Comments(int eventId)
            {
            CommentsBL commentsBL = new CommentsBL();
            IEnumerable<Comment> comments= commentsBL.GetComments(eventId);
            return PartialView(new CommentToCommentModelHelper().GetCommentModels(comments));
            }

     
        
        [HttpPost]
        public ActionResult AddCommentsPost([Bind(Include ="EventId,CommentAdded")]CommentModel commentModel)
            {
            commentModel.Date = DateTime.Now;
                if(ModelState.IsValid)
                {
                new AddCommentsBL().AddComment(new CommentModelToCommentHelper().CommentModelToCommentMapping(commentModel));
                }
            return RedirectToAction("ViewEvent",new { commentModel.EventId});
            }
            
    }
}

MVCAssignment/Views/BookReadingEvent/AllEvents.cshtml
@using MVCAssignment.Models
@using System.Collections.Generic;
@model IEnumerable<EventModel>
@{
    ViewBag.Title = "AllEvents";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AllEvents</h2>
<h2>MissedEvents</h2>
<div class="container">
    @{
        <ul>
            @foreach (var item in Model)
                {

                <li>@Html.ActionLink(@item.Title, "ViewEvent", "BookReadingEvent", new { @item.EventId }, null)</li>

                }
        </ul>
    }
</div>

MVCAssignment/Views/BookReadingEvent/Comments.cshtml
@using MVCAssignment.Models
@model IEnumerable<CommentModel>
    @{
        <div class="container">
            @foreach(var item in Model)
                {
                    <div>
                       <p> @item.CommentAdded    Posted On  @item.Date.Date</p>
                    </div>
                }
        </div>

    }

MVCAssignment/Views/BookReadingEvent/CreateEvent.cshtml
@model MVCAssignment.Models.EventModel
@using Shared;
@using MVCAssignment.Models
@{
    ViewBag.Title = "CreateEvent";
   
}

<div class="container center-block">
    <h2>CreateEvent</h2>

    @using (Html.BeginForm("CreateEvent","BookReadingEvent",FormMethod.Post))
        {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>EventModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                <div>
                    @ViewBag.Message;
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OtherDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.OtherDetails, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.OtherDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.RadioButtonFor(model => model.Type, EventType.PUBLIC)@Html.Label("Public")<br />
                @Html.RadioButtonFor(model => model.Type, EventType.PRIVATE)@Html.Label("Private")<br />
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InviteByEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.InviteByEmail, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.InviteByEmail, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>

        }
    </div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

MVCAssignment/Views/BookReadingEvent/CreateEventPost.cshtml
@model MVCAssignment.Models.EventModel

@{
    ViewBag.Title = "CreateEventPost";
   
}

<h2>CreateEventPost</h2>

@using (Html.BeginForm("CreateEvent","BookReadingEvent",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EventModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })


                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OtherDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OtherDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OtherDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InviteByEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InviteByEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InviteByEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div class="container">
    <h3>@ViewBag.EventCreated</h3>
</div>

MVCAssignment/Views/BookReadingEvent/EditEvent.cshtml
@model MVCAssignment.Models.EventModel

@{
    ViewBag.Title = "EditEvent";
    }

<h2>EditEvent</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>EventModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.EventId)
    @Html.HiddenFor(model => model.UserId)

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control " } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control datepicker " } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OtherDetails, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OtherDetails, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OtherDetails, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.InviteByEmail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.InviteByEmail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.InviteByEmail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>

}

MVCAssignment/Views/BookReadingEvent/EventsInvitedTo.cshtml
@using MVCAssignment.Models
@using System.Collections.Generic
@model IEnumerable<EventModel>
@{
    ViewBag.Title = "InvitedTo";
    
}

<h2>Events Invited To</h2>
<div class="container">
    @{
        <ul>
            @foreach (var item in Model)
                {
                
                    <li>@Html.ActionLink(@item.Title, "ViewEvent", "BookReadingEvent",new { @item.EventId },null)</li>
               
                }
        </ul>
    }
</div>

MVCAssignment/Views/BookReadingEvent/MissedEvents.cshtml
@using MVCAssignment.Models
@using System.Collections.Generic;
@model IEnumerable<EventModel>

@{
    ViewBag.Title = "MissedEvents";
}

<h2>MissedEvents</h2>
<div class="container">
    @{
        <ul>
            @foreach (var item in Model)
                {
                
                    <li>@Html.ActionLink(@item.Title, "ViewEvent", "BookReadingEvent", new {  @item.EventId }, null)</li>
                
                }
        </ul>
    }
</div>

MVCAssignment/Views/BookReadingEvent/MyEvents.cshtml
@using MVCAssignment.Models
@using System.Collections.Generic
@model IEnumerable<EventModel>
@{
    ViewBag.Title = "MyEvents";
   
}

<h2>MyEvents</h2>
<div class="container">
    @{
        <ul>
            @foreach (var item in Model)
                {
                
                    <li>@Html.ActionLink(@item.Title, "ViewEvent", "BookReadingEvent",new { eventId=@item.EventId},null)</li>
                
                }
        </ul>
    }
</div>

MVCAssignment/Views/BookReadingEvent/UpcomingEvents.cshtml
@using System.Collections.Generic
@using MVCAssignment.Models
@model IEnumerable<EventModel>

    
@{
    ViewBag.Title = "UpcomingEvents";
}

<h2>UpcomingEvents</h2>
<div class="container">
    @{
        <ul>
            @foreach (var item in Model)
                {
                
                    <li>@Html.ActionLink(@item.Title, "ViewEvent", "BookReadingEvent", new { @item.EventId },null)</li>
                
                }
        </ul>
    }
</div>

MVCAssignment/Views/BookReadingEvent/ViewEvent.cshtml
@using MVCAssignment.Models
@model EventModel
@{
    ViewBag.Title = "ViewEvent";
}


<h2>ViewEvent</h2>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)

        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StartTime)

        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)

        </dd>
        @if (ViewBag.DisplayDuration)
            {
            <dt>
                @Html.DisplayNameFor(model => model.Duration)

            </dt>

            <dd>
                @Html.DisplayFor(model => model.Duration)

            </dd>
            }
        @if (ViewBag.DisplayOtherDetails)
            {
            <dt>
                @Html.DisplayNameFor(model => model.OtherDetails)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OtherDetails)
            </dd>
            }
        @if (ViewBag.DisplayCount)
            {
            <dt>
                @Html.DisplayNameFor(model => model.Count)

            </dt>

            <dd>
                @Html.DisplayFor(model => model.Count)

            </dd>
            }
        @if (ViewBag.DisplayDescription)
            {
            <dt>
                @Html.DisplayNameFor(model => model.Description)

            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)

            </dd>
            }
    </dl>
    <div>
        @if (ViewBag.DisplayEditLink && User.Identity.IsAuthenticated)
            {
            @Html.ActionLink("Edit", "EditEvent", "BookReadingEvent", new { eventId = Model.EventId }, null)
            }
        @if (User.IsInRole("Admin"))
            {
            @Html.ActionLink("Delete", "DeleteEvent", "BookReadingEvent", new { eventId = Model.EventId }, null)
            }
    </div>


    @using (Html.BeginForm("AddCommentsPost", "BookReadingEvent", FormMethod.Post))
        {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>CommentModel</h4>
            <hr />
            @Html.HiddenFor(model => model.EventId);

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CommentAdded, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CommentAdded, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Post" class="btn btn-default" />
                </div>
            </div>
        </div>
        }

    <p>
        @Html.Action("Comments", new { Model.EventId })
    </p>
    
</div>